### ISSUE TITLE
Let's come up with a tagline!

### ISSUE THREAD

**Issue by githubteacher** [github-scholars/atlanta#24]
Please suggest a tagline for the front of our web site!

**Comment by IsaiahJ1** [comment]
Black and College Bound

**Comment by JoshuaMarshall1** [comment]
"Make Atlanta Great Again!!!""

**Comment by IriqM** [comment]
The github greats

**Comment by KefentseN** [comment]
Lets Make Atlanta Great again!!

**Comment by powerman592** [comment]
Make Henry Great again

**Comment by jaydint1** [comment]
Code is the new Cool 🆒

**Comment by JarralT** [comment]
Lets Make Github Great

**Comment by JordanGastion1** [comment]
The journey on Atlanta tech evolution

**Comment by AnnaR1** [comment]
GitHub Awesomeness 👍

**Comment by IriqM** [comment]
Code Town

**Comment by IriqM** [comment]
Changing The Culture

**Comment by KidaneM1** [comment]
Tech Is The New Black

**Comment by JaydinG1** [comment]
Coding For Everyone also boneless pizza

**Comment by KaylaF1** [comment]
♥❤👌✌♈ Noice

**Comment by KrystalW1** [comment]
Github is awesome

**Comment by KellisB** [comment]
Github life

**Comment by HenryWill** [comment]
college bound coding

**Comment by JustinBCB4** [comment]
New Atlanta 🔥 🔥 🔥

**Comment by IsaiahJ1** [comment]
Github Coding Inc. (Free Cookies)

**Comment by JaydinG1** [comment]
Make coding great again for African Americans

**Comment by IriqM** [comment]
Changing The Culture

**Comment by IsaiahJ1** [comment]
Be Innovative and make yourselves known!!!

**Comment by HenryWill** [comment]
Henrys Coding Classes

**Comment by githubteacher** [comment]
> Tech Is The New Black

This is our chosen tagline!

**Comment by Sa-naiH** [comment]
Tech way or no way
