### ISSUE TITLE
Please change the subtext.

### ISSUE THREAD

**Issue by githubteacher** [github-scholars/atlanta#26]
Can we choose a new subtext? Please ✋  if you want to work on this.

**Comment by powerman592** [comment]
Coded by Github Scholars

**Comment by IsaiahJ1** [comment]
Hey i want to work on this

**Comment by KidaneM1** [comment]
I want to work on this

**Comment by KefentseN** [comment]
Hey guys I want to work on this

**Comment by KrystalW1** [comment]
I want to work on this.

**Comment by JarralT** [comment]
I want to work on this

**Comment by JaydinG1** [comment]
i wanna work on this

**Comment by KefentseN** [comment]
Github Scholars can be our subtext

**Comment by IsaiahJ1** [comment]
The Black Minority becomes the Majority

**Comment by KidaneM1** [comment]
Bringing The Tech Experience To All

**Comment by powerman592** [comment]
We changed the subtext successfully guys!
