### ISSUE TITLE
Please change background image

### ISSUE THREAD

**Issue by githubteacher** [github-scholars/atlanta#27]
Can we choose a new background image? Please ✋  if you want to work on this.

**Comment by HenryWill** [comment]
Make it a computer chip

**Comment by DaChristianW** [comment]
i want to work on this

**Comment by JoshuaMarshall1** [comment]
Hey I want to work on this.

**Comment by ChelseaB1** [comment]
i want to work on this

**Comment by SierraC** [comment]
hey i want to work on this

**Comment by IriqM** [comment]
me

**Comment by Sa-naiH** [comment]
hey i want to work on this

**Comment by JordanGastion1** [comment]
I want to work on the background image! ✋

**Comment by KaylaF1** [comment]
I want to work on this

**Comment by AnnaR1** [comment]
I'd like to work on this.

**Comment by IriqM** [comment]
hey i want to work on this

**Comment by KellisB** [comment]
this one

**Comment by JustinBCB4** [comment]
i want to on this

**Comment by IriqM** [comment]
is everyone looking up images for the background

**Comment by JordanGastion1** [comment]
https://us.123rf.com/450wm/rawpixel/rawpixel1512/rawpixel151206876/49264732-students-learning-education-social-media-technology.jpg?ver=6

**Comment by KaylaF1** [comment]
![](https://s-media-cache-ak0.pinimg.com/236x/7e/f9/3c/7ef93cda57b922c378caba9d173a3c16--orange-wallpaper-fabric-wallpaper.jpg)

**Comment by JustinBCB4** [comment]
![image](https://user-images.githubusercontent.com/30048968/28122753-2199b71e-66ed-11e7-9146-4bd2cef3c1c9.png)

**Comment by DaChristianW** [comment]
![Uploading image.png…]()

**Comment by DaChristianW** [comment]
![]
(https://mail.google.com/mail/u/0/?ui=2&ik=70039c3de9&view=fimg&th=15d3733d79ebd9a1&attid=0.3&disp=inline&realattid=b43cf7dbbc0b5338_0.1.1&safe=1&attbid=ANGjdJ8rH0Iyj9R4nUa9aqaf3vHKxsz7cHXx-3l-zvmDFIo5A4Wi4_XUCGK7-IExGdh1MZQvtD1TQ2-gSNT8aPc9BL5r2z_x_evNIcxWr3sHEAEqyR8pAvcOCD0LipU&ats=1499869734352&rm=15d3733d79ebd9a1&zw&sz=w1920-h937)

**Comment by DaChristianW** [comment]
![] 
(https://mail.google.com/mail/u/0/?ui=2&ik=70039c3de9&view=fimg&th=15d3733d79ebd9a1&attid=0.3&disp=inline&realattid=b43cf7dbbc0b5338_0.1.1&safe=1&attbid=ANGjdJ8rH0Iyj9R4nUa9aqaf3vHKxsz7cHXx-3l-zvmDFIo5A4Wi4_XUCGK7-IExGdh1MZQvtD1TQ2-gSNT8aPc9BL5r2z_x_evNIcxWr3sHEAEqyR8pAvcOCD0LipU&ats=1499869734352&rm=15d3733d79ebd9a1&zw&sz=w1920-h937)

**Comment by JustinBCB4** [comment]
![image](https://user-images.githubusercontent.com/30048968/28122837-5ce492bc-66ed-11e7-9142-3e38975bdf6f.png)

**Comment by ChelseaB1** [comment]
![]
(https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-407970.jpg)

**Comment by DaChristianW** [comment]
![] 
(https://mail.google.com/mail/u/0/?ui=2&ik=70039c3de9&view=fimg&th=15d3733d79ebd9a1&attid=0.3&disp=inline&realattid=b43cf7dbbc0b5338_0.1.1&safe=1&attbid=ANGjdJ8rH0Iyj9R4nUa9aqaf3vHKxsz7cHXx-3l-zvmDFIo5A4Wi4_XUCGK7-IExGdh1MZQvtD1TQ2-gSNT8aPc9BL5r2z_x_evNIcxWr3sHEAEqyR8pAvcOCD0LipU&ats=1499869734352&rm=15d3733d79ebd9a1&zw&sz=w1920-h937)

**Comment by hectorsector** [comment]
This is done, so closing.
